spring:
  application:
    name: Gateway-service
  cloud:
    gateway:
      routes:
        - id: r1
          uri: http://localhost:8083/
          predicates:
            - Path=/users/**
            
      discovery:        locator:          enabled: false
server:  port: 8087

eureka:  client:    enabled: true
    fetch-registry: true
    register-with-eureka: true